### ISSUE TITLE
layout直接写yogalayout

### ISSUE THREAD

**Issue by kelciej** [koudle/AndYogaExample#2]
你好，
本人刚涉足yoga，按照facebook yoga 文档上面配置的yoga 环境
gradle ：
    compile 'com.facebook.yoga:yoga:1.2.0'
    compile 'com.facebook.yoga.android:yoga-layout:1.2.0'

layout.xml：
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:yoga="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >
    <com.facebook.yoga.android.YogaLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        yoga:padding_all="20dp"
        yoga:flex_direction="row"
        yoga:align_items="center"
        >
    </com.facebook.yoga.android.YogaLayout>

</RelativeLayout>

但是每次跑程序的时候，都提示 找不到 yogalayout。

所以想向您咨询一下，谢谢啦

**Comment by kelciej** [comment]
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.facebook.yoga.android.YogaLayout 


FATAL EXCEPTION: main
                                                   Process: com.example.jiangjia.yogatest, PID: 28991
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.jiangjia.yogatest/com.example.jiangjia.yogatest.MainActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class com.facebook.yoga.android.YogaLayout
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5072)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.facebook.yoga.android.YogaLayout
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
                                                       at android.app.Activity.setContentView(Activity.java:1947)
                                                       at com.example.jiangjia.yogatest.MainActivity.onCreate(MainActivity.java:17)
                                                       at android.app.Activity.performCreate(Activity.java:5249)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:141) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5072) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:597)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
                                                       at android.app.Activity.setContentView(Activity.java:1947) 
                                                       at com.example.jiangjia.yogatest.MainActivity.onCreate(MainActivity.java:17) 
                                                       at android.app.Activity.performCreate(Activity.java:5249) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:141) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5072) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.NoClassDefFoundError: com.facebook.soloader.SoLoader
                                                       at com.facebook.yoga.YogaNode.<clinit>(YogaNode.java:24)
                                                       at com.facebook.yoga.android.YogaLayout.<init>(YogaLayout.java:87)
                                                       at com.facebook.yoga.android.YogaLayout.<init>(YogaLayout.java:81)
                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:597) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
                                                       at android.app.Activity.setContentView(Activity.java:1947) 
                                                       at com.example.jiangjia.yogatest.MainActivity.onCreate(MainActivity.java:17) 
                                                       at android.app.Activity.performCreate(Activity.java:5249) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:141) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5072) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
04-11 14:44:47.118 28991-28991/? I/Process: Sending signal. PID: 28991 SIG: 9

**Comment by koudle** [comment]
@kelciej 
Caused by: java.lang.NoClassDefFoundError: com.facebook.soloader.SoLoader
因为你还有依赖库没有添加
